const moves = [

{
    id:1,

    kind:"通常",

    name:"は？",
    
    kana:"は？",

    type:"おとこ",

    category:"特殊",

    power:100,

    accuracy:100,

    pp:8,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:false,

    protect:true,

    drain:0,

    effect:`
通常攻撃。
`
},

{
    id:2,

    kind:"通常",

    name:"は？きもすぎだろ",
    
    kana:"は？きもすぎだろ",

    type:"おとこ",

    category:"物理",

    power:80,

    accuracy:100,

    pp:15,

    target:"2体",

    priority:0,

    critical:0,

    contact:true,

    protect:true,

    drain:0,

    effect:`
ランダムな相手2体に攻撃する。
`
},

{
    id:3,

    kind:"通常",

    name:"は？うざすぎだろ",
    
    kana:"は？うざすぎだろ",

    type:"おとこ",

    category:"物理",

    power:60,

    accuracy:100,

    pp:10,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:true,

    protect:true,

    drain:0,

    effect:`
63%の確率で攻撃が2段階上がる。
`
},

{
    id:4,

    kind:"通常",

    name:"は？ふざけんなよ",
    
    kana:"は？ふざけんなよ",

    type:"おとこ",

    category:"変化",

    power:0,

    accuracy:100,

    pp:10,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:false,

    protect:true,

    drain:0,

    effect:`
相手単体の防御を3段階下げる。
`
},

{
    id:5,

    kind:"通常",

    name:"はやぶ三連撃",
  
    kana:"はやぶさんれんげき",

    type:"おとこ",

    category:"物理",

    power:30,

    accuracy:100,

    pp:15,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:true,

    protect:true,

    drain:0,

    effect:`
相手単体に3回連続で攻撃する。
`
},

{
    id:6,

    kind:"通常",

    name:"は？ポテチに決まってんだろ",
  
    kana:"は？ぽてちにきまってんだろ",

    type:"おとこ",

    category:"特殊",

    power:60,

    accuracy:100,

    pp:20,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:false,

    protect:true,

    drain:0,

    effect:`
自身のHPを最大HPの40%分回復する。
`
},

{
  id: 201,
  kind: "通常",
  name: "神速",
  kana: "しんそく",
  type: "無",
  category: "物理",
  power: 80,
  accuracy: 100,
  pp: 5,
  target: "相手単体",
  priority: 2,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "優先度+2で攻撃する。"
},
{
  id: 202,
  kind: "通常",
  name: "大爆発",
  kana: "だいばくはつ",
  type: "無",
  category: "物理",
  power: 250,
  accuracy: 100,
  pp: 5,
  target: "自分以外",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "自分以外の全員が対象。攻撃後、自身が死亡する。"
},
{
  id: 203,
  kind: "通常",
  name: "スピードスター",
  kana: "すぴーどすたー",
  type: "無",
  category: "特殊",
  power: 80,
  accuracy: 101,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "通常攻撃。"
},
{
  id: 204,
  kind: "通常",
  name: "トライアタック",
  kana: "とらいあたっく",
  type: "無",
  category: "特殊",
  power: 80,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "20%の確率で相手を麻痺、炎上、氷結のいずれかにする。"
},
{
  id: 205,
  kind: "通常",
  name: "カウンター",
  kana: "かうんたー",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手1体",
  priority: -5,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "優先度-5。相手から受けた物理ダメージを2倍にして返す。"
},
{
  id: 206,
  kind: "通常",
  name: "守る",
  kana: "まもる",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "自分",
  priority: 4,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "そのターン相手の技を受けない。連続使用不可。"
},
{
  id: 207,
  kind: "通常",
  name: "身代わり",
  kana: "みがわり",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "最大HPの1/4を消費し、そのHPと同じHPの身代わりを作る。身代わりがある間は身代わり貫通技以外を代わりに受ける。"
},
{
  id: 208,
  kind: "通常",
  name: "剣の舞",
  kana: "つるぎのまい",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の攻撃を2段階上げる。"
},
{
  id: 209,
  kind: "通常",
  name: "羽休め",
  kana: "はねやすめ",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 5,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "最大HPの半分回復する。使用したターンは大地技が当たるようになる。"
},
{
  id: 210,
  kind: "通常",
  name: "瞑想",
  kana: "めいそう",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の特攻・特防を1段階上げる。"
},
{
  id: 211,
  kind: "通常",
  name: "瞬迅",
  kana: "しゅんじん",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 15,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の攻撃・速度を1段階上げる。"
},
{
  id: 212,
  kind: "通常",
  name: "指を振る",
  kana: "ゆびをふる",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "ほぼ全ての通常技の中からランダムに1つ使用する。奥義・Z技は出ない。"
},
{
  id: 213,
  kind: "通常",
  name: "バトンタッチ",
  kana: "ばとんたっち",
  type: "無",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "控えのキャラクターと交代し、能力ランク・身代わり・命血・呪い・アクアリングを引き継ぐ。"
},
{
id: 214,
  kind: "通常",
  name: "フレアドライブ",
  kana: "ふれあどらいぶ",
  type: "炎",
  category: "物理",
  power: 120,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "相手に与えたダメージの3分の1を受ける。10%の確率で相手を炎上状態にする。"
},
{
id: 215,
  kind: "通常",
  name: "ニトロチャージ",
  kana: "にとろちゃーじ",
  type: "炎",
  category: "物理",
  power: 50,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "自身の速度を1段階上げる。"
},

{
  id: 216,
  kind: "通常",
  name: "大文字",
  kana: "だいもんじ",
  type: "炎",
  category: "特殊",
  power: 110,
  accuracy: 85,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を炎上状態にする。"
},
{
  id: 217,
  kind: "通常",
  name: "火炎放射",
  kana: "かえんほうしゃ",
  type: "炎",
  category: "特殊",
  power: 90,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を炎上状態にする。"
},
{
  id: 218,
  kind: "通常",
  name: "鬼火",
  kana: "おにび",
  type: "炎",
  category: "変化",
  power: 0,
  accuracy: 85,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "炎属性以外の相手を炎上状態にする。"
},
{
  id: 219,
  kind: "通常",
  name: "蛍火",
  kana: "ほたるび",
  type: "炎",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の特攻を2段階上げる。"
},

{
  id: 220,
  kind: "通常",
  name: "ボルテッカー",
  kana: "ぼるてっかー",
  type: "雷",
  category: "物理",
  power: 120,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "相手に与えたダメージの3分の1を受ける。10%の確率で相手を麻痺状態にする。"
},
{
  id: 221,
  kind: "通常",
  name: "ワイルドボルト",
  kana: "わいるどぼると",
  type: "雷",
  category: "物理",
  power: 90,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "相手に与えたダメージの4分の1を受ける。"
},
{
  id: 222,
  kind: "通常",
  name: "10万ボルト",
  kana: "じゅうまんボルト",
  type: "雷",
  category: "特殊",
  power: 90,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を麻痺状態にする。"
},
{
  id: 223,
  kind: "通常",
  name: "ボルトチェンジ",
  kana: "ぼるとちぇんじ",
  type: "雷",
  category: "特殊",
  power: 70,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "攻撃後、控えと交代する。"
},
{
  id: 224,
  kind: "通常",
  name: "電磁波",
  kana: "でんじは",
  type: "雷",
  category: "変化",
  power: 0,
  accuracy: 90,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "雷、大地属性以外の相手を麻痺状態にする。"
},
{
  id: 225,
  kind: "通常",
  name: "充電",
  kana: "じゅうでん",
  type: "雷",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "次使う雷属性の技の威力が2倍になる。自身の特防を1段階上げる。"
},
{
  id: 226,
  kind: "通常",
  name: "アクアブレイク",
  kana: "あくあぶれいく",
  type: "水",
  category: "物理",
  power: 85,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "20%の確率で相手の防御を1段階下げる。"
},
{
  id: 227,
  kind: "通常",
  name: "クイックターン",
  kana: "くいっくたーん",
  type: "水",
  category: "物理",
  power: 60,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "攻撃後、控えと交代する。"
},
{
  id: 228,
  kind: "通常",
  name: "ハイドロポンプ",
  kana: "はいどろぽんぷ",
  type: "水",
  category: "特殊",
  power: 110,
  accuracy: 80,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "通常攻撃。"
},
{
  id: 229,
  kind: "通常",
  name: "渦潮",
  kana: "うずしお",
  type: "水",
  category: "特殊",
  power: 35,
  accuracy: 85,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "4〜5ターンの間、毎ターン終了時に最大HPの1/8ダメージを与える。その間ゴースト属性以外のキャラクターは交代できない。"
},
{
  id: 230,
  kind: "通常",
  name: "アクアリング",
  kana: "あくありんぐ",
  type: "水",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "使用後、毎ターンHPが最大HPの1/16ずつ回復する。"
},
{
  id: 231,
  kind: "通常",
  name: "命の雫",
  kana: "いのちのしずく",
  type: "水",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "味方全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "仲間全員のHPをそれぞれ最大HPの1/4回復する。特性『貯水』のキャラクターには無効。"
},
{
  id: 232,
  kind: "通常",
  name: "アクロバット",
  kana: "あくろばっと",
  type: "風",
  category: "物理",
  power: 55,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "自身が持ち物を持っていない時、ダメージが2倍になる。"
},
{
  id: 233,
  kind: "通常",
  name: "ダブルウィンド",
  kana: "だぶるうぃんど",
  type: "風",
  category: "物理",
  power: 40,
  accuracy: 90,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "2回連続で攻撃する。"
},
{
  id: 234,
  kind: "通常",
  name: "エアスラッシュ",
  kana: "えあすらっしゅ",
  type: "風",
  category: "特殊",
  power: 75,
  accuracy: 95,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率でスタンさせる。"
},
{
  id: 235,
  kind: "通常",
  name: "エアカッター",
  kana: "えあかったー",
  type: "風",
  category: "特殊",
  power: 70,
  accuracy: 95,
  pp: 20,
  target: "相手全体",
  priority: 0,
 critical: 30,
  contact: false,
  protect: true,
  drain: 0,
  effect: "通常攻撃。"
},
{
  id: 236,
  kind: "通常",
  name: "追い風",
  kana: "おいかぜ",
  type: "風",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 15,
  target: "味方全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "4ターンの間味方全員の速度が2倍になる。"
},
{
  id: 237,
  kind: "通常",
  name: "安らぎの風",
  kana: "やすらぎのかぜ",
  type: "風",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "味方全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "仲間全員のHPをそれぞれ最大HPの1/5回復し、速度を1段階上げる。"
},

{
  id: 238,
  kind: "通常",
  name: "吸血",
  kana: "きゅうけつ",
  type: "ブラッド",
  category: "物理",
  power: 80,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 50,
  effect: "相手に与えたダメージの半分だけ自身のHPが回復する。"
},
{
  id: 239,
  kind: "通常",
  name: "裂傷",
  kana: "れっしょう",
  type: "ブラッド",
  category: "物理",
  power: 50,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "相手を必ず出血させる。"
},
{
  id: 240,
  kind: "通常",
  name: "ブラッドムーン",
  kana: "ぶらっどむーん",
  type: "ブラッド",
  category: "特殊",
  power: 120,
  accuracy: 100,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "連続使用不可。"
},
{
  id: 241,
  kind: "通常",
  name: "ブラッドウェーブ",
  kana: "ぶらっどうぇーぶ",
  type: "ブラッド",
  category: "特殊",
  power: 95,
  accuracy: 100,
  pp: 10,
  target: "相手全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を出血させる。"
},
{
  id: 242,
  kind: "通常",
  name: "力を吸い取る",
  kana: "ちからをすいとる",
  type: "ブラッド",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の攻撃の値と同じ値分HPを回復し、相手の攻撃を1段階下げる。既に最大まで下がっている場合は失敗する。"
},
{
  id: 243,
  kind: "通常",
  name: "命血",
  kana: "めいけつ",
  type: "ブラッド",
  category: "変化",
  power: 0,
  accuracy: 90,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "使用後、毎ターン相手のHPを最大HPの1/8ずつ減らし、その分自身のHPを回復させる。自身が交代してもこの効果は引き継がれる。"
},

{
  id: 244,
  kind: "通常",
  name: "月華一閃",
  kana: "げっかいっせん",
  type: "月",
  category: "物理",
  power: 40,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 1,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "優先度+1で攻撃する。"
},
{
  id: 245,
  kind: "通常",
  name: "ムーンスラッシュ",
  kana: "むーんすらっしゅ",
  type: "月",
  category: "物理",
  power: 25,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "2〜5回連続で攻撃する。"
},
{
  id: 246,
  kind: "通常",
  name: "ムーンフォース",
  kana: "むーんふぉーす",
  type: "月",
  category: "特殊",
  power: 95,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手の特攻を1段階下げる。"
},
{
  id: 247,
  kind: "通常",
  name: "玉輪光線",
  kana: "ぎょくりんこうせん",
  type: "月",
  category: "特殊",
  power: 150,
  accuracy: 90,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "使用した次のターンは行動できない。"
},
{
  id: 248,
  kind: "通常",
  name: "月の光",
  kana: "つきのひかり",
  type: "月",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 5,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身のHPを最大HPの半分回復する。"
},
{
  id: 249,
  kind: "通常",
  name: "月華の舞",
  kana: "げっかのまい",
  type: "月",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 15,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の特攻と速度を1段階上げる。"
},
{
  id: 250,
  kind: "通常",
  name: "威光",
  kana: "いこう",
  type: "月",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の攻撃を2段階下げる。"
},

{
  id: 251,
  kind: "通常",
  name: "氷の礫",
  kana: "こおりのつぶて",
  type: "氷",
  category: "物理",
  power: 40,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 1,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "優先度+1で攻撃する。"
},
{
  id: 252,
  kind: "通常",
  name: "氷柱落とし",
  kana: "つららおとし",
  type: "氷",
  category: "物理",
  power: 85,
  accuracy: 90,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手をスタンさせる。"
},
{
  id: 253,
  kind: "通常",
  name: "冷凍ビーム",
  kana: "れいとうビーム",
  type: "氷",
  category: "特殊",
  power: 90,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を氷結状態にする。"
},
{
  id: 254,
  kind: "通常",
  name: "フリーズドライ",
  kana: "ふりーずどらい",
  type: "氷",
  category: "特殊",
  power: 70,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手を氷結状態にする。水属性の相手にも弱点を突ける。"
},
{
  id: 255,
  kind: "通常",
  name: "オーロラベール",
  kana: "おーろらべーる",
  type: "氷",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "味方の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "3ターンの間、相手の物理・特殊攻撃のダメージを半分にする。ダブル・トリプルバトルでは半分ではなく2/3になる。会心攻撃は軽減できない。氷属性のキャラクターしか使用できない。"
},
{
  id: 256,
  kind: "通常",
  name: "黒い霧",
  kana: "くろいきり",
  type: "氷",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 30,
  target: "全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "場にいる全員のステータス変化をリセットする。"
},

{
  id: 257,
  kind: "通常",
  name: "影打ち",
  kana: "かげうち",
  type: "ゴースト",
  category: "物理",
  power: 40,
  accuracy: 100,
  pp: 30,
  target: "相手単体",
  priority: 1,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "優先度+1で攻撃する。"
},
{
  id: 258,
  kind: "通常",
  name: "お墓参り",
  kana: "おはかまいり",
  type: "ゴースト",
  category: "物理",
  power: 50,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "死亡した味方のキャラクター1体につき威力が50上昇する。"
},
{
  id: 259,
  kind: "通常",
  name: "祟り目",
  kana: "たたりめ",
  type: "ゴースト",
  category: "特殊",
  power: 65,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手が状態異常なら威力が2倍になる。"
},
{
  id: 260,
  kind: "通常",
  name: "シャドーボール",
  kana: "しゃどーぼーる",
  type: "ゴースト",
  category: "特殊",
  power: 80,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "20%の確率で相手の特防を1段階下げる。"
},
{
  id: 261,
  kind: "通常",
  name: "呪い",
  kana: "のろい",
  type: "ゴースト",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身がゴースト属性なら最大HPの半分を消費して相手を呪い状態にする。呪い状態の相手は毎ターン最大HPの1/4ダメージを受ける。それ以外の属性の場合は自身の速度が1段階下がり、攻撃・防御が1段階上がる。"
},
{
  id: 262,
  kind: "通常",
  name: "道連れ",
  kana: "みちづれ",
  type: "ゴースト",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 5,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "次の自身のターンまでに相手の攻撃で死亡した場合、相手も死亡する。連続使用不可。"
},

{
  id: 263,
  kind: "通常",
  name: "バリアーラッシュ",
  kana: "ばりあーらっしゅ",
  type: "聖",
  category: "物理",
  power: 60,
  accuracy: 90,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "攻撃後、自身の防御を1段階上げる。"
},
{
  id: 264,
  kind: "通常",
  name: "閃光",
  kana: "せんこう",
  type: "聖",
  category: "物理",
  power: 70,
  accuracy: 100,
  pp: 5,
  target: "相手単体",
  priority: 1,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "優先度+1で攻撃する。相手が攻撃技以外を選択していた場合は失敗する。"
},
{
  id: 265,
  kind: "通常",
  name: "アシストパワー",
  kana: "あしすとぱわー",
  type: "聖",
  category: "特殊",
  power: 20,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "自身の能力ランク上昇1つにつき威力が20上昇する。"
},
{
  id: 266,
  kind: "通常",
  name: "マジカルシャイン",
  kana: "まじかるしゃいん",
  type: "聖",
  category: "特殊",
  power: 80,
  accuracy: 100,
  pp: 10,
  target: "相手全体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "通常攻撃。"
},
{
  id: 267,
  kind: "通常",
  name: "ミラーコート",
  kana: "みらーこーと",
  type: "聖",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: -5,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "優先度-5。相手から受けた特殊ダメージを2倍にして返す。"
},
{
  id: 268,
  kind: "通常",
  name: "コスモパワー",
  kana: "こすもぱわー",
  type: "聖",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の防御・特防を1段階上げる。"
},
{
  id: 269,
  kind: "通常",
  name: "光の壁",
  kana: "ひかりのかべ",
  type: "聖",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "味方の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "5ターンの間、味方全員が受ける特殊攻撃のダメージを半分にする。ダブル・トリプルバトルでは半分ではなく2/3になる。会心攻撃は軽減できない。"
},
{
  id: 270,
  kind: "通常",
  name: "リフレクター",
  kana: "りふれくたー",
  type: "聖",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "味方の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "5ターンの間、味方全員が受ける物理攻撃のダメージを半分にする。ダブル・トリプルバトルでは半分ではなく2/3になる。会心攻撃は軽減できない。"
},

{
  id: 271,
  kind: "通常",
  name: "地獄突き",
  kana: "じごくづき",
  type: "闇",
  category: "物理",
  power: 20,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "自身の能力ランク上昇1つにつき威力が20上昇する。"
},
{
  id: 272,
  kind: "通常",
  name: "アビスメテオ",
  kana: "あびすめてお",
  type: "闇",
  category: "物理",
  power: 65,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の持ち物をなくす。持ち物を持っている相手を攻撃した場合、威力が1.5倍になる。"
},
{
  id: 273,
  kind: "通常",
  name: "悪の波動",
  kana: "あくのはどう",
  type: "闇",
  category: "特殊",
  power: 80,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "20%の確率で相手をスタンさせる。"
},
{
  id: 274,
  kind: "通常",
  name: "ナイトバースト",
  kana: "ないとばーすと",
  type: "闇",
  category: "特殊",
  power: 85,
  accuracy: 95,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
 contact: false,
  protect: true,
  drain: 0,
  effect: "40%の確率で相手を暗闇状態にする。"
},
{
  id: 275,
  kind: "通常",
  name: "悪魔の囁き",
  kana: "あくまのささやき",
  type: "闇",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "3ターンの間、相手は攻撃技しか使えなくなる。"
},
{
  id: 276,
  kind: "通常",
  name: "深淵の残響",
  kana: "しんえんのざんきょう",
  type: "闇",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の攻撃と特攻を1段階下げ、その後控えのキャラクターと交代する。身代わりを貫通する。"
},
{
  id: 277,
  kind: "通常",
  name: "魔力吸収",
  kana: "まりょくきゅうしゅう",
  type: "闇",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の特攻を2段階下げる。"
},

{
  id: 278,
  kind: "通常",
  name: "アイアンブレード",
  kana: "あいあんぶれーど",
  type: "鋼",
  category: "物理",
  power: 80,
  accuracy: 100,
  pp: 15,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手をスタンさせる。"
},
{
  id: 279,
  kind: "通常",
  name: "バレットパンチ",
  kana: "ばれっとぱんち",
  type: "鋼",
  category: "物理",
  power: 40,
  accuracy: 100,
  pp: 30,
  target: "相手単体",
  priority: 1,
 critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "優先度+1で攻撃する。"
},
{
  id: 280,
  kind: "通常",
  name: "ラスターカノン",
  kana: "らすたーかのん",
  type: "鋼",
  category: "特殊",
  power: 80,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手の特防を1段階下げる。"
},
{
  id: 281,
  kind: "通常",
  name: "徹底光線",
  kana: "てっていこうせん",
  type: "鋼",
  category: "特殊",
  power: 140,
  accuracy: 95,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "攻撃後、自身のHPを最大HPの半分だけ減らす。攻撃を防がれた場合でも自身のHPは減る。"
},
{
  id: 282,
  kind: "通常",
  name: "メタルバースト",
  kana: "めたるばーすと",
  type: "鋼",
  category: "変化",
  power: 0,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "最後に受けたダメージを1.5倍にして相手に返す。"
},
{
  id: 283,
  kind: "通常",
  name: "鉄壁",
  kana: "てっぺき",
  type: "鋼",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 15,
  target: "自分",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "自身の防御を2段階上げる。"
},

{
  id: 284,
  kind: "通常",
  name: "毒突き",
  kana: "どくづき",
  type: "毒",
  category: "物理",
  power: 80,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: true,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手を毒状態にする。"
},
{
  id: 285,
  kind: "通常",
  name: "ダストシュート",
  kana: "だすとしゅーと",
  type: "毒",
  category: "物理",
  power: 120,
  accuracy: 80,
  pp: 5,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手を毒状態にする。"
},
{
  id: 286,
  kind: "通常",
  name: "アシッドボム",
  kana: "あしっどぼむ",
  type: "毒",
  category: "特殊",
  power: 40,
  accuracy: 100,
  pp: 20,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "相手の特防を2段階下げる。"
},
{
  id: 287,
  kind: "通常",
  name: "ヘドロ爆弾",
  kana: "へどろばくだん",
  type: "毒",
  category: "特殊",
  power: 90,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手を毒状態にする。"
},
{
  id: 288,
  kind: "通常",
  name: "毒毒",
  kana: "どくどく",
  type: "毒",
  category: "変化",
  power: 0,
  accuracy: 90,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "鋼、毒属性以外の相手を猛毒状態にする。毒属性のキャラクターが使用した場合は必中になる。"
},
{
  id: 289,
  kind: "通常",
  name: "毒菱",
  kana: "どくびし",
  type: "毒",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "相手の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "相手の場を毒菱状態にする。相手が交代して召喚されたキャラクターを毒状態にする。2回使うと猛毒状態になる。特性『浮遊』のキャラクターは毒状態にならない。毒属性のキャラクターが召喚されると毒菱は消える。"
},

{
  id: 290,
  kind: "通常",
  name: "地震",
  kana: "じしん",
  type: "大地",
  category: "物理",
  power: 100,
  accuracy: 100,
  pp: 10,
  target: "自分以外全員",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "自分以外の全員を攻撃する。"
},
{
  id: 291,
  kind: "通常",
  name: "ドリルライナー",
  kana: "どりるらいなー",
  type: "大地",
  category: "物理",
  power: 80,
  accuracy: 95,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 30,
  contact: true,
  protect: true,
  drain: 0,
  effect: "通常攻撃。"
},
{
  id: 292,
  kind: "通常",
  name: "大地の力",
  kana: "だいちのちから",
  type: "大地",
  category: "特殊",
  power: 90,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "10%の確率で相手の特防を1段階下げる。"
},
{
  id: 293,
  kind: "通常",
  name: "熱砂の大地",
  kana: "ねっさのだいち",
  type: "大地",
  category: "特殊",
  power: 70,
  accuracy: 100,
  pp: 10,
  target: "相手単体",
  priority: 0,
 critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "30%の確率で相手を炎上状態にする。自身が氷結状態でも使用でき、氷結状態が治る。"
},
{
  id: 294,
  kind: "通常",
  name: "撒菱",
  kana: "まきびし",
  type: "大地",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "相手の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "相手の場を撒菱状態にする。3回まで重ね掛けでき、相手が交代して召喚された時に最大HPの1/8、1/6、1/4のダメージを与える。特性『浮遊』や風船を持ったキャラクターはダメージを受けない。"
},
{
  id: 295,
  kind: "通常",
  name: "ステルスグランド",
  kana: "すてるすぐらんど",
  type: "大地",
  category: "変化",
  power: 0,
  accuracy: 0,
  pp: 20,
  target: "相手の場",
  priority: 0,
  critical: 0,
  contact: false,
  protect: null,
  drain: 0,
  effect: "相手の場をステルスグランド状態にする。相手が交代して召喚された時に最大HPの1/8のダメージを与える。受けるダメージは属性相性の影響を受ける。(特性『浮遊』や風船で浮いてるキャラクターにも命中する。)"
},

{
    id:2001,

    kind:"奥義",

    name:"アルティメットはやぶサンダー",
  
    kana:"あるてぃめっとはやぶさんだー",

    type:"おとこ",

    category:"特殊",

    power:150,

    accuracy:100,

    pp:0,

    target:"相手全体",

    priority:0,

    critical:0,

    contact:false,

    protect:true,

    drain:0,

    effect:`
通常攻撃。
`
},

{
    id:3001,

    kind:"Z技",

    name:"スーパーポテチアタック",
  
    kana:"すーぱーぽてちあたっく",

    type:"おとこ",

    category:"物理",

    power:186,

    accuracy:101,

    pp:1,

    target:"相手単体",

    priority:0,

    critical:0,

    contact:false,

    protect:true,

    drain:0,

    effect:`
使用者の攻撃、特攻を1段階上げる。
`
},

{
  id: 3501,
  kind: "Z技",
  name: "オムニバース・ゼロ",
  kana: "おむにばーす・ぜろ",
  type: "無",
  category: "不明",
  power: 200,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "無属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3502,
  kind: "Z技",
  name: "ブレイジングインフェルノバーン",
  kana: "ぶれいじんぐいんふぇるのばーん",
  type: "炎",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "炎属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3503,
  kind: "Z技",
  name: "サンダーボルトスマッシュ",
  kana: "さんだーぼるとすまっしゅ",
  type: "雷",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "雷属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3504,
  kind: "Z技",
  name: "アビスオーシャンストリーム",
  kana: "あびすおーしゃんすとりーむ",
  type: "水",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
 critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "水属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3505,
  kind: "Z技",
  name: "アルティメットヴォルテックス",
  kana: "あるてぃめっとゔぉるてっくす",
  type: "風",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "風属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3506,
  kind: "Z技",
  name: "デスブラッディフォース",
  kana: "ですぶらっでぃふぉーす",
  type: "ブラッド",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "ブラッド属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3507,
  kind: "Z技",
  name: "月影終焉連斬",
  kana: "げつえいしゅうえんれんざん",
  type: "月",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "月属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},

{
  id: 3508,
  kind: "Z技",
  name: "ファイナルフィンブルブリザード",
  kana: "ふぁいなるふぃんぶるぶりざーど",
  type: "氷",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "氷属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3509,
  kind: "Z技",
  name: "死への黄泉の導き",
  kana: "しへのよみのみちびき",
  type: "ゴースト",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "ゴースト属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3510,
  kind: "Z技",
  name: "インフィニティラジェーション",
  kana: "いんふぃにてぃらじぇーしょん",
  type: "聖",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "聖属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3511,
  kind: "Z技",
  name: "ブラックホールディザスター",
  kana: "ぶらっくほーるでぃざすたー",
  type: "闇",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "闇属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3512,
  kind: "Z技",
  name: "殲滅鋼鉄光線",
  kana: "せんめつこうてつこうせん",
  type: "鋼",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "鋼属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3513,
  kind: "Z技",
  name: "終焉の毒刃斬撃",
  kana: "しゅうえんのどくじんざんげき",
  type: "毒",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "毒属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},
{
  id: 3514,
  kind: "Z技",
  name: "ギガグランドカタストロフィ",
  kana: "ぎがぐらんどかたすとろふぃ",
  type: "大地",
  category: "不明",
  power: 180,
  accuracy: 101,
  pp: 1,
  target: "相手単体",
  priority: 0,
  critical: 0,
  contact: false,
  protect: true,
  drain: 0,
  effect: "大地属性のZ技。元の技によって分類が変化する。(物理なら物理になり、特殊なら特殊になる。変化技はZ技として使用不可。)"
},

];